amcl:
  ros__parameters:
    base_frame_id: "base_link"         # The frame attached to the robot’s body
    odom_frame_id: "odom"         # The odometry frame
    global_frame_id: "map"          # The global reference frame
    scan_topic: "/scan"        # The laser scan topic (must match your sensor)
    min_particles: 500      # Number of particles in the filter
    max_particles: 2000
    update_min_d: 0.2      # Minimum distance change to update particles
    update_min_a: 0.2      # Minimum angle change to update particles
    laser_max_range: 10.0    # Maximum range of the laser
    laser_z_hit: 0.5       # Weight for correct range measurements
    laser_z_short: 0.1    # Weight for short readings
    laser_z_max: 0.05   # Weight for max range readings
    laser_z_rand: 0.05   # Weight for random noise
    laser_sigma: 0.2     # Standard deviation of the laser
    max_beams: 60       # Maximum beams to consider
